#pragma once
#include <string>

std::string defaultConfiguration = "[game]\n"
	"skin = Default\n"
	"audiopitch = 0\n"
	"framelimit = 144\n"
	"fps = 5\n"
	"audiooffset = 0\n"
	"audiovolume = 50\n"
	"autosound = 1\n"
	"resolution = 1280x960\n"
	"renderer = 0\n"
	"guideline = 2\n\n"

	"[keymapping]\n"
	"lane1 = A\n"
	"lane2 = S\n"
	"lane3 = D\n"
	"lane4 = Space\n"
	"lane5 = J\n"
	"lane6 = K\n"
	"lane7 = L\n"
	"6_lane1 = A\n"
	"6_lane2 = S\n"
	"6_lane3 = F\n"
	"6_lane4 = J\n"
	"6_lane5 = K\n"
	"6_lane6 = L\n"
	"5_lane1 = A\n"
	"5_lane2 = S\n"
	"5_lane3 = Space\n"
	"5_lane4 = K\n"
	"5_lane5 = L\n"
	"4_lane1 = A\n"
	"4_lane2 = S\n"
	"4_lane3 = K\n"
	"4_lane4 = L\n"
	"notespeedup = F4\n"
	"notespeeddown = F3\n\n"

	"[music]\n"
	"folder =\n"

	"[gameplay]\n"
	"notespeed = 225\n";